### ISSUE TITLE
exception in package

### ISSUE THREAD

**Issue by KekeliDev** [alex-melnyk/flutter_advanced_drawer#40]
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Container(bg: Color(0x00000000)):
No Directionality widget found.
Stack widgets require a Directionality widget ancestor to resolve the 'alignment' argument.
The default value for 'alignment' is AlignmentDirectional.topStart, which requires a text direction.
The specific widget that could not find a Directionality ancestor was:
  Stack
The ownership chain for the affected widget is: "Stack ← ColoredBox ← Container ← Listener ←
  _GestureSemantics ← RawGestureDetector ← GestureDetector ← IgnorePointer ← DefaultTextStyle ←
  AnimatedDefaultTextStyle ← ⋯"
Typically, the Directionality widget is introduced by the MaterialApp or WidgetsApp widget at the
top of your application widget tree. It determines the ambient reading direction and is used, for
example, to determine how to lay out text, how to interpret "start" and "end" values, and to resolve
EdgeInsetsDirectional, AlignmentDirectional, and other *Directional objects.
Instead of providing a Directionality widget, another solution would be passing a non-directional
'alignment', or an explicit 'textDirection', to the Stack.

The relevant error-causing widget was:
  Container
  Container:file:///Users/kekeli/.pub-cache/hosted/pub.dev/flutter_advanced_drawer-1.3.3/lib/src/widget.
  dart:133:18

When the exception was thrown, this was the stack:
#0      debugCheckHasDirectionality.<anonymous closure> (package:flutter/src/widgets/debug.dart:354:7)
#1      debugCheckHasDirectionality (package:flutter/src/widgets/debug.dart:374:4)
#2      Stack._debugCheckHasDirectionality (package:flutter/src/widgets/basic.dart:3887:14)
#3      Stack.createRenderObject (package:flutter/src/widgets/basic.dart:3899:12)
#4      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5817:52)
#5      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6519:11)
...     Normal element mounting (91 frames)
#96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#98     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#99     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
#100    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
(package:flutter/src/widgets/binding.dart:1092:18)
#101    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)
#102    RenderObjectToWidgetAdapter.attachToRenderTree
(package:flutter/src/widgets/binding.dart:1091:13)
#103    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
#104    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>
(package:flutter/src/widgets/binding.dart:906:7)
#108    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 3 frames from class _Timer and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by alex-melnyk** [comment]
Please update to the latest version, the plugin isn't use `IgnorePointer` anymore
