### ISSUE TITLE
AnimationController.forward() called after AnimationController.dispose()

### ISSUE THREAD

**Issue by amrogad** [alex-melnyk/flutter_advanced_drawer#43]
Seems you guys already worked on this in a previous version but even after upgrading to the latest version 1.3.5 I'm still getting it.

```
════════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for AdvancedDrawerController:
AnimationController.forward() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
'package:flutter/src/animation/animation_controller.dart':
animation_controller.dart:1
Failed assertion: line 459 pos 7: '_ticker != null'


When the exception was thrown, this was the stack
#2      AnimationController.forward
animation_controller.dart:459
#3      _AdvancedDrawerState._handleControllerChanged
widget.dart:245
#4      ChangeNotifier.notifyListeners
change_notifier.dart:381
#5      ValueNotifier.value=
change_notifier.dart:495
#6      AdvancedDrawerController.showDrawer
controller.dart:11
#7      SBScaffoldDrawerAnimationState.handleMenuButtonPressed
sb_scaffold_drawer_animation.dart:102
#8      _InkResponseState.handleTap
ink_well.dart:1096
#9      GestureRecognizer.invokeCallback
recognizer.dart:253
#10     TapGestureRecognizer.handleTapUp
tap.dart:627
#11     BaseTapGestureRecognizer._checkUp
tap.dart:306
#12     BaseTapGestureRecognizer.acceptGesture
tap.dart:276
#13     GestureArenaManager.sweep
arena.dart:163
#14     GestureBinding.handleEvent
binding.dart:464
#15     GestureBinding.dispatchEvent
binding.dart:440
#16     RendererBinding.dispatchEvent
binding.dart:336
#17     GestureBinding._handlePointerEventImmediately
binding.dart:395
#18     GestureBinding.handlePointerEvent
binding.dart:357
#19     GestureBinding._flushPointerEventQueue
binding.dart:314
#20     GestureBinding._handlePointerDataPacket
binding.dart:295
#21     _invoke1 (dart:ui/hooks.dart:164:13)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided 2 frames from class _AssertionError)
The AdvancedDrawerController sending notification was: AdvancedDrawerController#78928(Instance of 'AdvancedDrawerValue')
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by foundation library ════════════════════════════════
AnimationController.forward() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
'package:flutter/src/animation/animation_controller.dart':
animation_controller.dart:1
Failed assertion: line 459 pos 7: '_ticker != null'
```

**Comment by burhanaksendir** [comment]
Hi @amrogad ,
I encountered a similar issue. Were you able to resolve the issue?

**Comment by amrogad** [comment]
@burhanaksendir  nope sorry, the project I had this issue with was abandoned, and no one was replying here anyway so I just closed the issue and moved on

**Comment by burhanaksendir** [comment]
I have prepared a pull request that resolves the problem. You can find the pull request [here](< https://github.com/alex-melnyk/flutter_advanced_drawer/pull/48 >).
